/**
 * ═══════════════════════════════════════════════════════════════
 * SPARK ITEM TYPES - AI-Generated Item Schema from "God Mode" Backend
 * ═══════════════════════════════════════════════════════════════
 * 
 * These types define the data structure for items generated by the
 * enhanced AI backend with rich metadata, subtasks, and scheduling.
 */

// ═══════════════════════════════════════════════════════════════
// TYPE DEFINITIONS
// ═══════════════════════════════════════════════════════════════

/** Available item types from AI classification */
export type SparkItemType =
    | 'task'
    | 'event'
    | 'learning'
    | 'idea'
    | 'habit'
    | 'fitness'
    | 'project';

/** Item status in the workflow */
export type SparkItemStatus =
    | 'todo'
    | 'inbox'
    | 'scheduled'
    | 'done';

/** Priority levels */
export type SparkItemPriority =
    | 'high'
    | 'medium'
    | 'low';

// ═══════════════════════════════════════════════════════════════
// SCHEDULING INTERFACE
// ═══════════════════════════════════════════════════════════════

/** Scheduling information for timed items */
export interface SparkScheduling {
    /** Due date in YYYY-MM-DD format */
    dueDate?: string;
    /** Time in HH:MM format */
    time?: string;
    /** Whether this item recurs */
    isRecurring?: boolean;
}

// ═══════════════════════════════════════════════════════════════
// META INFORMATION INTERFACE
// ═══════════════════════════════════════════════════════════════

/** Rich metadata generated by AI analysis */
export interface SparkMeta {
    /** Original URL for links/learning items */
    url?: string | null;
    /** Estimated time to complete (e.g., "15m", "2h") */
    estimatedDuration?: string;
    /** Reading time for articles (e.g., "5 min read") */
    readingTime?: string;
    /** Sentiment analysis result */
    sentiment?: string;
    /** AI's explanation for classification decisions */
    aiReasoning?: string;
    /** Author name for articles/books */
    author?: string;
}

// ═══════════════════════════════════════════════════════════════
// MAIN SPARK ITEM INTERFACE
// ═══════════════════════════════════════════════════════════════

/**
 * SparkItem - Complete item structure from AI "God Mode" backend
 * 
 * This interface captures all fields generated by the enhanced AI
 * analysis including task breakdown, scheduling, and meta-analysis.
 */
export interface SparkItem {
    /** Firebase Document ID */
    id: string;

    /** Item title/name */
    title: string;

    /** Main description or summary */
    content: string;

    /** AI-classified item type */
    type: SparkItemType;

    /** Current status in workflow */
    status: SparkItemStatus;

    /** Priority level */
    priority: SparkItemPriority;

    /** 
     * Array of subtask strings 
     * @example ["Buy milk", "Pay cashier"]
     */
    subtasks?: string[];

    /** 
     * Array of tags for categorization 
     * @example ["#finance", "#home"]
     */
    tags?: string[];

    /** Scheduling information */
    scheduling?: SparkScheduling;

    /** Rich AI-generated metadata */
    meta?: SparkMeta;

    /** Creation timestamp (ISO string) */
    createdAt: string;
}

// ═══════════════════════════════════════════════════════════════
// TYPE GUARDS
// ═══════════════════════════════════════════════════════════════

/** Check if an item has valid subtasks */
export function hasSubtasks(item: SparkItem): boolean {
    return Array.isArray(item.subtasks) && item.subtasks.length > 0;
}

/** Check if an item has AI metadata */
export function hasMeta(item: SparkItem): boolean {
    return item.meta !== undefined && item.meta !== null;
}

/** Check if an item is a learning type with URL */
export function isLearningWithUrl(item: SparkItem): boolean {
    return item.type === 'learning' && Boolean(item.meta?.url);
}

/** Check if an item has scheduling info */
export function hasScheduling(item: SparkItem): boolean {
    return item.scheduling !== undefined &&
        (Boolean(item.scheduling.dueDate) || Boolean(item.scheduling.time));
}

/** Check if an item has tags */
export function hasTags(item: SparkItem): boolean {
    return Array.isArray(item.tags) && item.tags.length > 0;
}
